### ISSUE TITLE
how to add failure block in async request?

### ISSUE THREAD

**Issue by cloudjanak** [happyMediumStl/iOSHttpHelper#1]

**Comment by mjvotaw** [comment]
Sorry I didn't get back to you before now, I was on holiday and didn't see this email come in.

Are you looking for something similar to NSURLConnectionDelegate's `connection:didFailWithError:` method?

NSUrlConnection's `sendAsynchronousRequest:` method doesn't have an error handler. Instead, the completionHandler will receive a non-null value for `connectionError` if some sort of connection error has occured. There's a pretty long list of possible errors, [you can see those here](http://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_Constants/Reference/reference.html#//apple_ref/doc/uid/TP40003793-CH3g-SW40).

**Comment by cloudjanak** [comment]
than how i can determine that request is success ?
Can you add one example please..

**Comment by mjvotaw** [comment]
You'll have to forgive me, this is an older project that we don't use internally anymore; we've been meaning to re-write it for some time, but haven't had a need. 

In any case, to catch failures, you'd do something like this:

```Objective-C
[HttpHelper sendAsyncGetRequestToURL:@"http://www.google.com" 
withParameters:nil
andCompletionHandler:^(NSURLResponse *response, NSData *data, NSError *error) {
if(error != nil)
{
    NSlog(@"Error occured: %@", error);
    return;
}
int statusCode = [((NSHTTPURLResponse *)response) statusCode];
if(statusCode == 404) /* server responded with 404 not found, you may also wish to check for 500 */
{
    NSLog(@"NSURLResponse returned 404");
    return;
}
/* NSURLConnection succeeded and received response from url */
NSString * dataString = [NSString alloc] initWithData:data encoding: NSUTF8StringEncoding];
NSLog(@"received data: %@", dataString);
/* perform whatever operations you need based on the returned data from the server */
}];
```

If `error` is nil, then the request succeeded, in the sense that your app sent the request to a URL and received some sort of response. It's also a good idea to check `response` to make sure the server responded with a non-error status code. If these conditions are met, then you can assume whatever `data` contains is a valid response data from the URL you hit.

Hope that helps, and sorry this isn't more apparent. NSURLConnection is kind of difficult to work with, and our hope was that this would make it at least somewhat less difficult.

**Comment by cloudjanak** [comment]
Thank you.
Its really helpful to me.
